apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-argo-application
  namespace: argocd
spec:
  project: default
  containers:
    - name: hello-world-app
      image: anoopri/hello-world-app:latest  # Update this image reference!
      ports:
        - containerPort: 3000
  

  source:
    repoURL: https://github.com/Starap3007/argodeploy.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-world-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
